function item = getStringFormat(h)
    % 1 5
    % 2 5
    % 3 5
    % 4 5
    item = [];
    % 6 7
    item(1.0).tlc_option_name = 'RSIM_SOLVER_SELECTION';
    item(1.0).make_var_name = 'RSIM_SOLVER_SELECTION';
    item(1.0).prop_name = 'RSIM_SOLVER_SELECTION';
    item(1.0).tlc_enum_in_num = true;
    item(1.0).make_enum_in_num = true;
    % 12 13
    item(2.0).tlc_option_name = '';
    item(2.0).make_var_name = 'PCMATLABROOT';
    item(2.0).prop_name = 'PCMatlabRoot';
    % 16 17
    item(3.0).tlc_option_name = 'ExtMode';
    item(3.0).make_var_name = 'EXT_MODE';
    item(3.0).prop_name = 'ExtMode';
    % 20 21
    item(4.0).tlc_option_name = 'ExtModeStaticAlloc';
    item(4.0).make_var_name = 'EXTMODE_STATIC_ALLOC';
    item(4.0).prop_name = 'ExtModeStaticAlloc';
    % 24 25
    item(5.0).tlc_option_name = 'ExtModeStaticAllocSize';
    item(5.0).make_var_name = 'EXTMODE_STATIC_ALLOC_SIZE';
    item(5.0).prop_name = 'ExtModeStaticAllocSize';
    % 28 29
    item(6.0).tlc_option_name = 'ExtModeTransport';
    item(6.0).make_var_name = 'EXTMODE_TRANSPORT';
    item(6.0).prop_name = 'ExtModeTransport';
    % 32 33
    item(7.0).tlc_option_name = 'ExtModeTesting';
    item(7.0).make_var_name = 'TMW_EXTMODE_TESTING';
    item(7.0).prop_name = 'ExtModeTesting';
    % 36 37
    item(8.0).tlc_option_name = 'RSIM_PARAMETER_LOADING';
    item(8.0).make_var_name = 'RSIM_PARAMETER_LOADING';
    item(8.0).prop_name = 'RSIM_PARAMETER_LOADING';
    % 40 41
    item(9.0).tlc_option_name = 'RTWCAPISignals';
    item(9.0).make_var_name = [];
    item(9.0).prop_name = 'RTWCAPISignals';
    % 44 45
    item(10.0).tlc_option_name = 'RTWCAPIParams';
    item(10.0).make_var_name = [];
    item(10.0).prop_name = 'RTWCAPIParams';
end % function
