function tgt = rtw_rsim_mdlref_compatibility(iTargetType)
    % 1 12
    % 2 12
    % 3 12
    % 4 12
    % 5 12
    % 6 12
    % 7 12
    % 8 12
    % 9 12
    % 10 12
    % 11 12
    tgt.Name = {[0.0],'invalid',{'Target'}};
    tgt.Description = {[2.0],''};
    tgt.Components = {[0.0],'invalid',{}};
    tgt.GenerateFullHeader = {[2.0],''};
    tgt.IsPILTarget = {[2.0],''};
    tgt.IsERTTarget = {[2.0],''};
    tgt.ModelReferenceCompliant = {[0.0],'invalid',{'on'}};
    tgt.RSIM_SOLVER_SELECTION = {[2.0],''};
    tgt.PCMatlabRoot = {[2.0],''};
    tgt.ExtMode = {[1.0],'not supported',{'off'}};
    tgt.ExtModeTransport = {[2.0],''};
    tgt.ExtModeStaticAlloc = {[2.0],''};
    tgt.ExtModeStaticAllocSize = {[2.0],''};
    tgt.ExtModeTesting = {[2.0],''};
    tgt.ExtModeMexFile = {[2.0],''};
    tgt.ExtModeMexArgs = {[2.0],''};
    tgt.ExtModeIntrfLevel = {[2.0],''};
end % function
