function rtwsampleconfig(cs)
    % 1 18
    % 2 18
    % 3 18
    % 4 18
    % 5 18
    % 6 18
    % 7 18
    % 8 18
    % 9 18
    % 10 18
    % 11 18
    % 12 18
    % 13 18
    % 14 18
    % 15 18
    % 16 18
    % 17 18
    stf = 'ert.tlc';
    tmf = 'ert_default_tmf';
    mc = 'make_rtw';
    % 21 24
    % 22 24
    % 23 24
    switchTarget(cs, stf, []);
    set_param(cs, 'TemplateMakefile', tmf);
    set_param(cs, 'MakeCommand', mc);
    % 27 28
    isERT = strcmp(get_param(cs, 'IsERTTarget'), 'on');
    % 29 32
    % 30 32
    % 31 32
    set_param(cs, 'TLCOptions', '-p0');
    % 33 36
    % 34 36
    % 35 36
    set_param(cs, 'SolverType', 'Fixed-step');
    set_param(cs, 'Solver', 'FixedStepDiscrete');
    if strcmp(get_param(cs, 'SolverType'), 'Fixed-step')
        set_param(cs, 'SolverMode', 'Auto');
        set_param(cs, 'AutoInsertRateTranBlk', 'on');
        % 41 42
    end % if
    % 43 46
    % 44 46
    % 45 46
    set_param(cs, 'BlockReduction', 'on');
    set_param(cs, 'ConditionallyExecuteInputs', 'on');
    set_param(cs, 'InlineParams', 'on');
    if strcmp(get_param(cs, 'InlineParams'), 'on')
        set_param(cs, 'InlineInvariantSignals', 'on');
        % 51 52
    end % if
    set_param(cs, 'BooleanDataType', 'on');
    set_param(cs, 'OptimizeBlockIOStorage', 'on');
    if strcmp(get_param(cs, 'OptimizeBlockIOStorage'), 'on')
        set_param(cs, 'LocalBlockOutputs', 'on');
        set_param(cs, 'BufferReuse', 'on');
        set_param(cs, 'ExpressionFolding', 'on');
    end % if
    set_param(cs, 'EnforceIntegerDowncast', 'off');
    % 61 62
    set_param(cs, 'RollThreshold', 5.0);
    set_param(cs, 'StateBitsets', 'on');
    % 64 65
    set_param(cs, 'DataBitsets', 'on');
    % 66 67
    set_param(cs, 'UseTempVars', 'on');
    % 68 69
    set_param(cs, 'FoldNonRolledExpr', 'on');
    % 70 71
    if isERT
        set_param(cs, 'ZeroExternalMemoryAtStartup', 'off');
        % 73 74
        set_param(cs, 'ZeroInternalMemoryAtStartup', 'off');
        % 75 76
        set_param(cs, 'InitFltsAndDblsToZero', 'off');
        set_param(cs, 'InlinedParameterPlacement', 'NonHierarchical');
        % 78 79
        set_param(cs, 'NoFixptDivByZeroProtection', 'on')
    end % if
    % 81 84
    % 82 84
    % 83 84
    set_param(cs, 'ProdHWDeviceType', 'Specified');
    set_param(cs, 'ProdBitPerChar', 8.0);
    set_param(cs, 'ProdBitPerShort', 16.0);
    set_param(cs, 'ProdBitPerInt', 32.0);
    set_param(cs, 'ProdBitPerLong', 32.0);
    set_param(cs, 'ProdWordSize', 32.0);
    set_param(cs, 'ProdIntDivRoundTo', 'Floor');
    % 91 92
    set_param(cs, 'ProdShiftRightIntArith', 'on');
    % 93 94
    set_param(cs, 'ProdEndianess', 'LittleEndian');
    % 95 98
    % 96 98
    % 97 98
    set_param(cs, 'GenerateReport', 'on');
    if strcmp(get_param(cs, 'GenerateReport'), 'on')
        set_param(cs, 'LaunchReport', 'on');
        if isERT
            set_param(cs, 'IncludeHyperlinkInReport', 'on');
        end % if
    end % if
    % 105 108
    % 106 108
    % 107 108
    set_param(cs, 'GenerateComments', 'on');
    if strcmp(get_param(cs, 'GenerateComments'), 'on')
        set_param(cs, 'SimulinkBlockComments', 'on');
        set_param(cs, 'ShowEliminatedStatement', 'off');
        set_param(cs, 'ForceParamTrailComments', 'on');
        % 113 114
        if isERT
            set_param(cs, 'InsertBlockDesc', 'on');
            set_param(cs, 'SimulinkDataObjDesc', 'on');
            % 117 118
        end % if
    end % if
    % 120 124
    % 121 124
    % 122 124
    % 123 124
    if isERT
        set_param(cs, 'MangleLength', 1.0);
        set_param(cs, 'CustomSymbolStrGlobalVar', 'rt$N$M');
        set_param(cs, 'CustomSymbolStrType', '$N$M');
        set_param(cs, 'CustomSymbolStrField', '$N$M');
        set_param(cs, 'CustomSymbolStrFcn', '$N$M$F');
        set_param(cs, 'CustomSymbolStrTmpVar', '$N$M');
        set_param(cs, 'CustomSymbolStrBlkIO', 'rtb_$N$M');
        set_param(cs, 'CustomSymbolStrMacro', '$N$M');
        set_param(cs, 'InlinedPrmAccess', 'Literals');
        set_param(cs, 'IgnoreCustomStorageClasses', 'off');
        % 135 138
        % 136 138
        % 137 138
    end % if
    % 139 142
    % 140 142
    % 141 142
    set_param(cs, 'GenFloatMathFcnCalls', 'ISO_C');
    % 143 145
    % 144 145
    if isERT
        set_param(cs, 'PurelyIntegerCode', 'on');
        % 147 148
        set_param(cs, 'SupportAbsoluteTime', 'off');
        set_param(cs, 'SupportComplex', 'off');
        set_param(cs, 'SupportContinuousTime', 'off');
        set_param(cs, 'SupportNonFinite', 'off');
        set_param(cs, 'SupportNonInlinedSFcns', 'off');
        set_param(cs, 'LifeSpan', '1');
    end % if
    % 155 158
    % 156 158
    % 157 158
    if isERT
        set_param(cs, 'IncludeMdlTerminateFcn', 'off');
        set_param(cs, 'MultiInstanceERTCode', 'off');
        set_param(cs, 'MultiInstanceErrorCode', 'Error');
        set_param(cs, 'RootIOFormat', 'Structure Reference');
        set_param(cs, 'SuppressErrorStatus', 'on');
        % 164 165
        set_param(cs, 'GRTInterface', 'off');
        set_param(cs, 'CombineOutputUpdateFcns', 'on');
    end % if
    % 168 171
    % 169 171
    % 170 171
    set_param(cs, 'RTWCAPIParams', 'off');
    set_param(cs, 'RTWCAPISignals', 'off');
    set_param(cs, 'GenerateASAP2', 'off');
    set_param(cs, 'ExtMode', 'off');
    % 175 178
    % 176 178
    % 177 178
    if isERT
        set_param(cs, 'ERTCustomFileTemplate', 'example_file_process.tlc');
        % 180 181
        set_param(cs, 'GenerateSampleERTMain', 'on');
        % 182 183
        set_param(cs, 'TargetOS', 'BareBoardExample');
        % 184 185
        set_param(cs, 'ERTSrcFileBannerTemplate', 'ert_code_template.cgt');
        % 186 187
        set_param(cs, 'ERTHdrFileBannerTemplate', 'ert_code_template.cgt');
        % 188 189
        set_param(cs, 'ERTDataSrcFileTemplate', 'ert_code_template.cgt');
        % 190 191
        set_param(cs, 'ERTDataHdrFileTemplate', 'ert_code_template.cgt');
        % 192 193
    end % if
    % 194 197
    % 195 197
    % 196 197
    if isERT
        set_param(cs, 'GenerateErtSFunction', 'off');
    end % if
    set_param(cs, 'MatFileLogging', 'off');
    set_param(cs, 'SaveTime', 'off');
    set_param(cs, 'SaveOutput', 'off');
    set_param(cs, 'SaveState', 'off');
    set_param(cs, 'SaveFinalState', 'off');
    % 205 208
    % 206 208
    % 207 208
    set_param(cs, 'RTWVerbose', 'off');
    set_param(cs, 'RetainRTWFile', 'off');
    set_param(cs, 'GenCodeOnly', 'on');
end % function
