function dlgStruct = getDialogSchema(this, name)
    % 1 7
    % 2 7
    % 3 7
    % 4 7
    % 5 7
    % 6 7
    dlgStruct = this.dlgMain(name, vertcat(cellhorzcat(this.hierGetDialogSchema(name)), cellhorzcat(this.dlgContainer(vertcat(cellhorzcat(this.dlgWidget('ShowJunctions')), cellhorzcat(this.dlgWidget('ShowTransitions')), cellhorzcat(this.dlgWidget('SkipAutogenerated'))), xlate('Children'))), cellhorzcat(this.list_getDialogSchema(name))));
    % 8 15
    % 9 15
    % 10 15
    % 11 15
    % 12 15
    % 13 15
    % 14 15
end % function
