function [nLeft, isAll] = hierLeft(this, thisNode)
    % 1 7
    % 2 7
    % 3 7
    % 4 7
    % 5 7
    if isa(thisNode, 'Stateflow.Machine')
        nLeft = rptgen_sf.csf_hier.hierSibling(thisNode, slroot, true);
        isAll = true;
    else
        if isa(thisNode, 'Stateflow.Chart')
            nLeft = rptgen_sf.csf_hier.hierSibling(thisNode, thisNode.Machine, true);
            isAll = true;
        else
            if isa(thisNode, 'Stateflow.Object')
                nLeft = left(thisNode);
                isAll = false;
                % 17 19
                if this.SkipAutogenerated && not(isempty(nLeft)) && not(rptgen_sf.isNotAutogenerated(nLeft))
                    % 19 22
                    % 20 22
                    [nLeft, isAll] = hierLeft(this, nLeft);
                end % if
            else
                % 24 26
                nLeft = [];
                isAll = false;
            end % if
        end % if
    end % if
