function schema
    % 1 10
    % 2 10
    % 3 10
    % 4 10
    % 5 10
    % 6 10
    % 7 10
    % 8 10
    pkgUD = findpackage('rptgen_ud');
    pkgSF = findpackage('rptgen_sf');
    % 11 13
    h = schema.class(pkgSF, 'csf_hier', pkgUD.findclass('cud_obj_hier'));
    % 13 15
    p = rptgen.prop(h, 'ShowTransitions', vertcat(cellhorzcat('all', xlate('All')), cellhorzcat('informative', xlate('Labeled or non-redundant')), cellhorzcat('nonredundant', xlate('Non-redundant')), cellhorzcat('labeled', xlate('Labeled')), cellhorzcat('none', xlate('None'))), 'informative', xlate('Show transitions'), 'SIMULINK_Report_Gen');
    % 15 25
    % 16 25
    % 17 25
    % 18 25
    % 19 25
    % 20 25
    % 21 25
    % 22 25
    % 23 25
    p = rptgen.prop(h, 'ShowJunctions', vertcat(cellhorzcat('all', xlate('All')), cellhorzcat('nonredundant', xlate('Non-redundant')), cellhorzcat('none', xlate('None'))), 'nonredundant', xlate('Show junctions'), 'SIMULINK_Report_Gen');
    % 25 34
    % 26 34
    % 27 34
    % 28 34
    % 29 34
    % 30 34
    % 31 34
    % 32 34
    p = rptgen.prop(h, 'SkipAutogenerated', 'bool', true, xlate('Skip autogenerated charts under truth tables'), 'SIMULINK_Report_Gen');
    % 34 39
    % 35 39
    % 36 39
    % 37 39
    rptgen.makeStaticMethods(h, {'hierSibling'}, {'hierGetPropsrc';'hierGetStartPoint';'hierUp';'hierDown';'hierLeft';'hierRight'});
    % 39 48
    % 40 48
    % 41 48
    % 42 48
    % 43 48
    % 44 48
    % 45 48
    % 46 48
