function S = InstGet
    % 1 13
    % 2 13
    % 3 13
    % 4 13
    % 5 13
    % 6 13
    % 7 13
    % 8 13
    % 9 13
    % 10 13
    % 11 13
    % 12 13
    allMPlay = MPlay.Find;
    S = [];
    for i=1.0:numel(allMPlay)
        this = allMPlay(i);
        % 17 19
        % 18 19
        T.source = this.Source;
        T.position = this.Position;
        T.docked = this.IsDocked;
        T.zoom = this.Magnification;
        T.zoomfit = this.FitToView;
        % 24 26
        % 25 26
        S(i).type = 'mplay';
        S(i).args = T;
    end % for
end % function
