function thisloadobj(this, s)
    % 1 8
    % 2 8
    % 3 8
    % 4 8
    % 5 8
    % 6 8
    % 7 8
    this.DifferentialDelay = s.DifferentialDelay;
    this.Fpass = s.Fpass;
    this.Astop = s.Astop;
end % function
