function loadFromBlock(this)
    % 1 10
    % 2 10
    % 3 10
    % 4 10
    % 5 10
    % 6 10
    % 7 10
    % 8 10
    % 9 10
    this.M = this.Block.M;
    this.OutType = this.Block.OutType;
    this.Dec = this.Block.Dec;
    this.PowType = this.Block.PowType;
    this.MinDist = this.Block.MinDist;
    this.AvgPow = this.Block.AvgPow;
    this.PeakPow = this.Block.PeakPow;
    this.outDtype1 = this.Block.outDtype1;
    this.outDtype2 = this.Block.outDtype2;
    % 19 21
    % 20 21
    this.denormFactorDTMode = this.Block.denormFactorDTMode;
    this.denormFactorWordLen = this.Block.denormFactorWordLen;
    this.prodOutDTMode = this.Block.prodOutDTMode;
    this.prodOutWordLen = this.Block.prodOutWordLen;
    this.prodOutRoundingMode = this.Block.prodOutRoundingMode;
    this.prodOutOverflowMode = this.Block.prodOutOverflowMode;
    this.sumDTMode = this.Block.sumDTMode;
    this.sumWordLen = this.Block.sumWordLen;
end % function
