function initialize(hObj, libName, libProduct, context)
    % 1 13
    % 2 13
    % 3 13
    % 4 13
    % 5 13
    % 6 13
    % 7 13
    % 8 13
    % 9 13
    % 10 13
    % 11 13
    error(nargchk(2.0, 4.0, nargin, 'struct'));
    % 13 15
    if lt(nargin, 3.0)
        pmDefaultProduct = pm_private('pm_defaultproduct');
        libProduct = pmDefaultProduct();
    end % if
    % 18 20
    if lt(nargin, 4.0)
        context = pmsl_defaultlibrary;
    end % if
    % 22 24
    hObj.Name = libName;
    hObj.Product = libProduct;
    hObj.Context = context;
    hObj.IsValid = false;
    hObj.RegistrationFile = '';
    hObj.Descriptor = hObj.Name;
    hObj.Icon = PmSli.Icon;
    % 30 32
    hObj.Icon.setText(hObj.Descriptor);
    % 32 38
    % 33 38
    % 34 38
    % 35 38
    % 36 38
    hObj.File = '';
    % 38 40
    hObj.DocumentationFcn = PmSli.LibraryEntry.defaultDocumentationFcn;
    % 40 42
