function loop_restoreState(h, oldState)
    % 1 8
    % 2 8
    % 3 8
    % 4 8
    % 5 8
    % 6 8
    % 7 8
    set(0.0, 'CurrentFigure', oldState.CurrentFigure);
    set(oldState.CurrentFigure, 'CurrentAxes', oldState.CurrentAxes);
end % function
