function init(this, block)
    % 1 8
    % 2 8
    % 3 8
    % 4 8
    % 5 8
    % 6 8
    % 7 8
    this.Block = block;
    this.CurrentTab = 0.0;
    this.DisableList = false;
    % 11 12
    parent = this.Block.getParent;
        while not(isa(parent, 'Simulink.BlockDiagram'))
        parent = parent.getParent;
    end % while
    this.Root = parent;
end % function
