function this = ToVcdBlock(block, dummy)
    % 1 9
    % 2 9
    % 3 9
    % 4 9
    % 5 9
    % 6 9
    % 7 9
    % 8 9
    this = hdllinkddg.ToVcdBlock(block);
    % 10 11
    this.Block = block;
    this.DisableList = false;
    % 13 14
    this.FileName = this.Block.FileName;
    this.NumInport = this.Block.NumInport;
    this.TimingScaleFactor = this.Block.TimingScaleFactor;
    this.TimingMode = this.Block.TimingMode;
    this.HdlTickScale = this.Block.HdlTickScale;
    this.HdlTickMode = this.Block.HdlTickMode;
    % 20 23
    % 21 23
    % 22 23
    parent = this.Block.getParent;
        while not(isa(parent, 'Simulink.BlockDiagram'))
        parent = parent.getParent;
    end % while
    this.Root = parent;
end % function
