function obj = OptFullAnalysis
    % 1 13
    % 2 13
    % 3 13
    % 4 13
    % 5 13
    % 6 13
    % 7 13
    % 8 13
    % 9 13
    % 10 13
    % 11 13
    % 12 13
    obj = dependencies.AnalysisOptions;
    obj.FindModelRefs = true;
    obj.FindLibraryLinks = true;
    obj.FindSFunctions = true;
    obj.FindCallbackFiles = true;
    obj.FindCodeGenFiles = true;
    obj.FindUserDependencies = true;
    obj.AllowUnsavedChanges = true;
    % 21 22
    obj.FindExplicitlyReferencedFiles = true;
    obj.AnalyzeStateflow = false;
    % 24 25
    obj.StoreReferences = true;
    obj.AnalyzeMathWorksFiles = false;
    % 27 28
    obj.SetReady;
end % function
