function obj = OptMdlsOnly
    % 1 12
    % 2 12
    % 3 12
    % 4 12
    % 5 12
    % 6 12
    % 7 12
    % 8 12
    % 9 12
    % 10 12
    % 11 12
    obj = dependencies.AnalysisOptions;
    % 13 14
    obj.FindModelRefs = true;
    obj.FindLibraryLinks = true;
    obj.AnalyzeMathWorksFiles = true;
    % 17 18
    obj.FindSFunctions = false;
    obj.FindCallbackFiles = false;
    obj.FindCodeGenFiles = false;
    obj.FindUserDependencies = false;
    obj.AllowUnsavedChanges = true;
    % 23 24
    obj.FindExplicitlyReferencedFiles = true;
    obj.AnalyzeStateflow = false;
    % 26 28
    % 27 28
    obj.StoreReferences = false;
    % 29 30
    obj.SetReady;
end % function
