function loadFromBlock(this)
    % 1 10
    % 2 10
    % 3 10
    % 4 10
    % 5 10
    % 6 10
    % 7 10
    % 8 10
    % 9 10
    this.Ph = this.Block.Ph;
    this.Dec = this.Block.Dec;
    this.OutType = this.Block.OutType;
    this.DecType = this.Block.DecType;
    this.VarSource = this.Block.VarSource;
    this.Variance = this.Block.Variance;
    this.outDtype1 = this.Block.outDtype1;
    this.outDtype2 = this.Block.outDtype2;
end % function
