function dlgStruct = loop_getDialogSchema(this, name)
    % 1 7
    % 2 7
    % 3 7
    % 4 7
    % 5 7
    % 6 7
    if not(builtin('license', 'checkout', 'SIMULINK_Report_Gen'))
        dlgStruct = this.buildErrorMessage('panel', true);
        return;
        % 10 11
    end % if
    % 12 13
    oTypes = {'isAndOrStates';'isBoxStates';'isFcnStates';'isTruthTables';'isEMFunctions'};
    % 14 22
    % 15 22
    % 16 22
    % 17 22
    % 18 22
    % 19 22
    % 20 22
    % 21 22
    if this.LockType
        typeContents = {};
        for i=length(oTypes):-1.0:1.0
            if get(this, oTypes{i})
                oProp = this.findprop(oTypes{i});
                typeContents = cellhorzcat(this.dlgText(oProp.Description));
                break
            end % if
        end % for
    else
        for i=length(oTypes):-1.0:1.0
            typeContents{i} = this.dlgWidget(oTypes{i});
        end % for
    end % if
    % 36 37
    dlgStruct = vertcat(cellhorzcat(this.dlgContainer(typeContents, xlate('State Types'))), cellhorzcat(this.dlgContainer(vertcat(cellhorzcat(this.dlgWidget('Depth', 'RowSpan', [1.0 1.0], 'ColSpan', [1.0 1.0])), cellhorzcat(this.dlgWidget('SkipAutogenerated', 'RowSpan', [2.0 2.0], 'ColSpan', [1.0 1.0])), cellhorzcat(RptgenML.twoColumnTable(this, 'SFFilterTerms', 'isSFFilterList', 'RowSpan', [3.0 3.0], 'ColSpan', [1.0 1.0]))), xlate('Loop Options'), 'LayoutGrid', [3.0 1.0], 'RowStretch', [0.0 0.0 1.0])));
    % 38 50
    % 39 50
    % 40 50
    % 41 50
    % 42 50
    % 43 50
    % 44 50
    % 45 50
    % 46 50
    % 47 50
    % 48 50
    % 49 50
end % function
