function Visible(mplayObj, vis)
    % 1 9
    % 2 9
    % 3 9
    % 4 9
    % 5 9
    % 6 9
    % 7 9
    % 8 9
    if lt(nargin, 2.0)
        vis = 'on';
    end % if
    set(mplayObj.widgetsObj.hfig, 'vis', vis);
end % function
