function dlgStruct = loop_getDialogSchema(this, name)
    % 1 7
    % 2 7
    % 3 7
    % 4 7
    % 5 7
    % 6 7
    if not(builtin('license', 'checkout', 'SIMULINK_Report_Gen'))
        dlgStruct = this.buildErrorMessage('panel', true);
        return;
        % 10 11
    end % if
    % 12 13
    dlgStruct = vertcat(cellhorzcat(this.dlgContainer(vertcat(cellhorzcat(this.dlgWidget('legibleFontSize', 'RowSpan', [1.0 1.0], 'ColSpan', [1.0 1.0])), cellhorzcat(this.dlgWidget('SkipAutogenerated', 'RowSpan', [2.0 2.0], 'ColSpan', [1.0 1.0])), cellhorzcat(RptgenML.twoColumnTable(this, 'SFFilterTerms', 'isSFFilterList', 'RowSpan', [3.0 3.0], 'ColSpan', [1.0 1.0]))), xlate('Loop Options'), 'LayoutGrid', [3.0 1.0], 'RowStretch', [0.0 0.0 1.0])));
    % 14 26
    % 15 26
    % 16 26
    % 17 26
    % 18 26
    % 19 26
    % 20 26
    % 21 26
    % 22 26
    % 23 26
    % 24 26
    % 25 26
end % function
