function schema
    % 1 9
    % 2 9
    % 3 9
    % 4 9
    % 5 9
    % 6 9
    % 7 9
    % 8 9
    pkg = findpackage('rptgen_sf');
    pkgRG = findpackage('rptgen');
    % 11 12
    h = schema.class(pkg, 'csf_hier_loop', pkgRG.findclass('rpt_looper'));
    % 13 15
    % 14 15
    p = rptgen.prop(h, 'legibleFontSize', 'double', 8.0, xlate('Minimum legible font size'), 'SIMULINK_Report_Gen');
    % 16 19
    % 17 19
    % 18 19
    p = rptgen.prop(h, 'SkipAutogenerated', 'bool', true, xlate('Skip autogenerated charts under truth tables'), 'SIMULINK_Report_Gen');
    % 20 23
    % 21 23
    % 22 23
    p = rptgen.prop(h, 'isSFFilterList', 'bool', false, xlate('Search Stateflow:'), 'SIMULINK_Report_Gen');
    % 24 27
    % 25 27
    % 26 27
    p = rptgen.prop(h, 'SFFilterTerms', 'string vector', {'Tag','MyTag'}, '', 'SIMULINK_Report_Gen');
    % 28 29
    p.Visible = 'off';
    % 30 34
    % 31 34
    % 32 34
    % 33 34
    rptgen.makeStaticMethods(h, {}, {'loop_getContextString';'loop_getLoopObjects';'loop_getObjectType';'loop_getPropSrc';'loop_restoreState';'loop_saveState';'loop_setState'});
    % 35 43
    % 36 43
    % 37 43
    % 38 43
    % 39 43
    % 40 43
    % 41 43
    % 42 43
end % function
