function out = getConfigOpt
    % 1 9
    % 2 9
    % 3 9
    % 4 9
    % 5 9
    % 6 9
    % 7 9
    % 8 9
    out = vertcat(cellhorzcat(xlate('Block reduction'), 'BlockReduction'), cellhorzcat(xlate('Implement logic signals as boolean data (vs. double)'), 'BooleanDataType'), cellhorzcat(xlate('Conditional input branch execution'), 'ConditionallyExecuteInputs'), cellhorzcat(xlate('Inline parameters'), 'InlineParams'), cellhorzcat(xlate('Application lifespan (days)'), 'LifeSpan'), cellhorzcat(xlate('Signals - Enable local block outputs'), 'LocalBlockOutputs'), cellhorzcat(xlate('Signals - Ignore integer downcasts in folded expressions'), 'EnforceIntegerDowncast'), cellhorzcat(xlate('Signals - Eliminate superfluous temporary variables (Expression folding)'), 'ExpressionFolding'), cellhorzcat(xlate('Signals - Reuse block outputs'), 'BufferReuse'), cellhorzcat(xlate('Signals - Inline invariant signals'), 'InlineInvariantSignals'), cellhorzcat(xlate('Signals - Loop unrolling threshold'), 'RollThreshold'), cellhorzcat(xlate('Integer and fixed-point - Remove code from floating-point to integer conversions that wraps out-of-range values'), 'EfficientFloat2IntCast'));
    % 10 31
    % 11 31
    % 12 31
    % 13 31
    % 14 31
    % 15 31
    % 16 31
    % 17 31
    % 18 31
    % 19 31
    % 20 31
    % 21 31
    % 22 31
    % 23 31
    % 24 31
    % 25 31
    % 26 31
    % 27 31
    % 28 31
    % 29 31
    % 30 31
end % function
