function this = NoHDLEmission(block)
    % 1 7
    % 2 7
    % 3 7
    % 4 7
    % 5 7
    % 6 7
    this = hdldefaults.NoHDLEmission;
    % 8 13
    % 9 13
    % 10 13
    % 11 13
    % 12 13
    supportedBlocks = {'built-in/SubSystem','built-in/Inport','built-in/Outport','built-in/Terminator','built-in/Scope','built-in/Display','built-in/ToFile','built-in/ToWorkspace','built-in/Assertion','built-in/Stop','simulink/Signal Attributes/Data Type Duplicate','simulink/Signal Attributes/Data Type Propagation','simulink/Sinks/XY Graph','dspsnks4/Signal To Workspace','dspsnks4/Vector Scope','dspsnks4/Spectrum Scope','dspsnks4/Waterfall','dspsnks4/Matrix Viewer','simulink/Model Verification/Check Discrete Gradient','simulink/Model Verification/Check  Dynamic Gap','simulink/Model Verification/Check  Dynamic Range','simulink/Model Verification/Check  Static Gap','simulink/Model Verification/Check  Static Range','simulink/Model Verification/Check Dynamic  Lower Bound','simulink/Model Verification/Check Dynamic  Upper Bound','simulink/Model Verification/Check Input  Resolution','simulink/Model Verification/Check Static  Lower Bound','simulink/Model Verification/Check Static  Upper Bound','modelsimlib/To VCD File','sflib/Truth Table','eml_lib/Embedded MATLAB Function'};
    % 14 48
    % 15 48
    % 16 48
    % 17 48
    % 18 48
    % 19 48
    % 20 48
    % 21 48
    % 22 48
    % 23 48
    % 24 48
    % 25 48
    % 26 48
    % 27 48
    % 28 48
    % 29 48
    % 30 48
    % 31 48
    % 32 48
    % 33 48
    % 34 48
    % 35 48
    % 36 48
    % 37 48
    % 38 48
    % 39 48
    % 40 48
    % 41 48
    % 42 48
    % 43 48
    % 44 48
    % 45 48
    % 46 48
    % 47 48
    oldsupportedBlocks = {};
    % 49 51
    % 50 51
    if eq(nargin, 0.0)
        block = '';
    end % if
    % 54 55
    desc = struct('ShortListing', 'No HDL emission', 'HelpText', 'No code generation via direct HDL emission');
    % 56 59
    % 57 59
    % 58 59
    this.init('SupportedBlocks', supportedBlocks, 'Block', block, 'Description', desc);
    % 60 61
end % function
