function childObj = count_getChildObjects(this, rootObj)
    % 1 8
    % 2 8
    % 3 8
    % 4 8
    % 5 8
    % 6 8
    if this.SkipAutogenerated
        filterTerms = cellhorzcat('-function', @isNotAutogenerated);
    else
        filterTerms = {};
    end % if
    % 12 14
    childObj = find(rootObj, '-isa', 'Stateflow.Object', filterTerms{:});
function tf = isNotAutogenerated(sfID)
    % 15 25
    % 16 25
    % 17 25
    % 18 25
    % 19 25
    % 20 25
    % 21 25
    % 22 25
    % 23 25
    tf = rptgen_sf.isNotAutogenerated(sfID);
