function modelEntry = newModelEntry
    % 1 7
    % 2 7
    % 3 7
    % 4 7
    % 5 7
    % 6 7
    modelEntry.model = [];
    modelEntry.modelData.registered = false;
    modelEntry.modelData.examining = false;
    modelEntry.modelData.preswitchCC = [];
    modelEntry.modelData.productsUsed = {};
    modelEntry.modelData.modelTopologyChecksum = {};
    modelEntry.modelData.isModelPreRtm = false;
    modelEntry.modelData.modelParameterChecksum = {};
    modelEntry.blockList = initializeBlockList;
    % 16 17
    modelEntry.modelOperation = initializeModelOperation;
end % function
