function initParams(this, varargin)
    % 1 8
    % 2 8
    % 3 8
    % 4 8
    % 5 8
    % 6 8
    % 7 8
    if eq(nargin, 3.0)
        this.EntityNameList = varargin{1.0};
        this.EntityPathList = varargin{2.0};
    else
        error(hdlcodererrormsgid('invalidargs'), 'Invalid Script Generator object instantiation');
        % 13 14
    end % if
    % 15 16
    this.TopLevelName = hdlentitytop;
    this.TestBenchName = hdlgetparameter('tb_name');
    this.TargetLanguage = hdlgetparameter('target_language');
    this.IsVHDL = hdlgetparameter('isvhdl');
    this.CodeGenDirectory = hdlgetparameter('codegendir');
    % 21 22
    this.GenerateCompileDoFile = hdlgetparameter('hdlcompilescript');
    this.GenerateTBCompileDoFile = hdlgetparameter('hdlcompiletb');
    this.GenerateSimDoFile = hdlgetparameter('hdlsimscript');
    this.GenerateSimProjectFile = hdlgetparameter('hdlsimprojectscript');
    this.GenerateSynthesisFile = hdlgetparameter('hdlsynthscript');
    this.GenerateMapFile = hdlgetparameter('hdlmapfile');
    % 28 29
    this.CompileDoFilePostFix = hdlgetparameter('hdlcompilefilepostfix');
    this.SimDoFilePostFix = hdlgetparameter('hdlsimfilepostfix');
    this.SimProjectFilePostFix = hdlgetparameter('hdlsimprojectfilepostfix');
    this.MapFilePostFix = hdlgetparameter('hdlmapfilepostfix');
    this.SynthesisFilePostFix = hdlgetparameter('hdlsynthfilepostfix');
    % 34 36
    % 35 36
    this.HdlCompileInit = hdlgetparameter('hdlcompileinit');
    this.HdlCompileVhdlCmd = hdlgetparameter('hdlcompilevhdlcmd');
    this.HdlCompileVerilogCmd = hdlgetparameter('hdlcompileverilogcmd');
    this.SimulatorFlags = hdlgetparameter('simulator_flags');
    this.HdlCompileTerm = hdlgetparameter('hdlcompileterm');
    this.HdlSimInit = hdlgetparameter('hdlsiminit');
    this.HdlSimCmd = hdlgetparameter('hdlsimcmd');
    this.HdlSimViewWaveCmd = hdlgetparameter('hdlsimviewwavecmd');
    this.HdlSimTerm = hdlgetparameter('hdlsimterm');
    this.HdlSimProjectInit = hdlgetparameter('hdlsimprojectinit');
    this.HdlSimProjectCmd = hdlgetparameter('hdlsimprojectcmd');
    this.HdlSimprojectTerm = hdlgetparameter('hdlsimprojectterm');
    this.HdlMapArrow = hdlgetparameter('hdlmaparrow');
    this.HdlSynthInit = hdlgetparameter('hdlsynthinit');
    this.HdlSynthCmd = hdlgetparameter('hdlsynthcmd');
    this.HdlSynthTerm = hdlgetparameter('hdlsynthterm');
    % 52 54
    % 53 54
    this.ScriptGenSuccessful = false;
end % function
