function loadFromBlock(this)
    % 1 10
    % 2 10
    % 3 10
    % 4 10
    % 5 10
    % 6 10
    % 7 10
    % 8 10
    % 9 10
    this.Radius = this.Block.Radius;
    this.Separation = this.Block.Separation;
    this.MuR = this.Block.MuR;
    this.EpsilonR = this.Block.EpsilonR;
    this.SigmaCond = this.Block.SigmaCond;
    this.SigmaDiel = this.Block.SigmaDiel;
    this.LineLength = this.Block.LineLength;
    this.StubMode = this.Block.StubMode;
    this.Termination = this.Block.Termination;
    % 19 21
    % 20 21
    this.SourceFreq = this.Block.SourceFreq;
    this.Freq = this.Block.Freq;
    this.AllPlotType = this.Block.AllPlotType;
    this.YOption = this.Block.YOption;
    this.XOption = this.Block.XOption;
    this.PlotZ0 = this.Block.PlotZ0;
end % function
