function thisloadobj(this, s)
    % 1 8
    % 2 8
    % 3 8
    % 4 8
    % 5 8
    % 6 8
    % 7 8
    this.F0 = s.F0;
    this.Q = s.Q;
    this.BW = s.BW;
    this.Apass = s.Apass;
    this.Astop = s.Astop;
end % function
