function thisloadobj(this, s)
    % 1 8
    % 2 8
    % 3 8
    % 4 8
    % 5 8
    % 6 8
    % 7 8
    this.F0 = s.F0;
    this.BW = s.BW;
    this.BWpass = s.BWpass;
    this.BWstop = s.BWstop;
    this.Flow = s.Flow;
    this.Fhigh = s.Fhigh;
    this.Gref = s.Gref;
    this.G0 = s.G0;
    this.GBW = s.GBW;
    this.Gpass = s.Gpass;
    this.Gstop = s.Gstop;
end % function
