function s = thissaveobj(this, s)
    % 1 8
    % 2 8
    % 3 8
    % 4 8
    % 5 8
    % 6 8
    % 7 8
    s.F0 = this.F0;
    s.BW = this.BW;
    s.BWpass = this.BWpass;
    s.BWstop = this.BWstop;
    s.Flow = this.Flow;
    s.Fhigh = this.Fhigh;
    s.Gref = this.Gref;
    s.G0 = this.G0;
    s.GBW = this.GBW;
    s.Gpass = this.Gpass;
    s.Gstop = this.Gstop;
end % function
