function dlgStruct = loop_getDialogSchema(this, name)
    % 1 7
    % 2 7
    % 3 7
    % 4 7
    % 5 7
    if not(builtin('license', 'checkout', 'SIMULINK_Report_Gen'))
        dlgStruct = this.buildErrorMessage('panel', true);
        return;
        % 9 11
    end % if
    % 11 13
    termTypes = listTerminalTypes(rptgen_sf.appdata_sf);
    if this.LockType
        oTypes = {};
        for i=1.0:length(termTypes)
            if get(this, horzcat('isReport', termTypes{i}))
                oTypes{plus(end, 1.0)} = this.dlgText(sprintf('Report on "%s" objects', termTypes{i}));
            end % if
        end % for
        if isempty(oTypes)
            % 21 24
            % 22 24
            oTypes{1.0} = this.dlgWidget('LockType', 'DialogRefresh', 1.0, 'Name', 'No types reported.  Uncheck to select object types');
            % 24 27
            % 25 27
        end % if
    else
        for i=length(termTypes):-1.0:1.0
            oTypes{i} = this.dlgWidget(horzcat('isReport', termTypes{i}));
        end % for
    end % if
    % 32 34
    dlgStruct = vertcat(cellhorzcat(this.dlgContainer(oTypes, xlate('Object Types'))), cellhorzcat(this.dlgContainer(vertcat(cellhorzcat(this.dlgWidget('Depth', 'RowSpan', [1.0 1.0], 'ColSpan', [1.0 1.0])), cellhorzcat(this.dlgWidget('SkipAutogenerated', 'RowSpan', [2.0 2.0], 'ColSpan', [1.0 1.0])), cellhorzcat(this.dlgWidget('RemoveRedundant', 'RowSpan', [3.0 3.0], 'ColSpan', [1.0 1.0])), cellhorzcat(RptgenML.twoColumnTable(this, 'SFFilterTerms', 'isSFFilterList', 'RowSpan', [4.0 4.0], 'ColSpan', [1.0 1.0]))), xlate('Loop Options'), 'LayoutGrid', [4.0 1.0], 'RowStretch', [0.0 0.0 0.0 1.0])));
    % 34 50
    % 35 50
    % 36 50
    % 37 50
    % 38 50
    % 39 50
    % 40 50
    % 41 50
    % 42 50
    % 43 50
    % 44 50
    % 45 50
    % 46 50
    % 47 50
    % 48 50
end % function
