function thisloadobj(this, s)
    % 1 8
    % 2 8
    % 3 8
    % 4 8
    % 5 8
    % 6 8
    % 7 8
    this.Fpass = s.Fpass;
    this.F6dB = s.F6dB;
    this.Fstop = s.Fstop;
    this.Apass = s.Apass;
    this.Astop = s.Astop;
    this.NumberOfSections = s.NumberOfSections;
    this.DifferentialDelay = s.DifferentialDelay;
    this.FrequencyConstraints = s.FrequencyConstraints;
    this.MagnitudeConstraints = s.MagnitudeConstraints;
end % function
