function compDesc = getDescription(thisComp)
    % 1 19
    % 2 19
    % 3 19
    % 4 19
    % 5 19
    % 6 19
    % 7 19
    % 8 19
    % 9 19
    % 10 19
    % 11 19
    % 12 19
    % 13 19
    % 14 19
    % 15 19
    % 16 19
    % 17 19
    % 18 19
    compDesc = xlate('Imports code generated by Real-Time Workshop and any custom files you specify as part of your model.');
end % function
