function loadFromBlock(this)
    % 1 10
    % 2 10
    % 3 10
    % 4 10
    % 5 10
    % 6 10
    % 7 10
    % 8 10
    % 9 10
    this.R = this.Block.R;
    this.L = this.Block.L;
    this.C = this.Block.C;
    this.G = this.Block.G;
    this.ParamFreq = this.Block.ParamFreq;
    this.InterpMethod = this.Block.InterpMethod;
    this.LineLength = this.Block.LineLength;
    this.StubMode = this.Block.StubMode;
    this.Termination = this.Block.Termination;
    % 19 21
    % 20 21
    this.SourceFreq = this.Block.SourceFreq;
    this.Freq = this.Block.Freq;
    this.AllPlotType = this.Block.AllPlotType;
    this.YOption = this.Block.YOption;
    this.XOption = this.Block.XOption;
    this.PlotZ0 = this.Block.PlotZ0;
end % function
