function loadFromBlock(this)
    % 1 10
    % 2 10
    % 3 10
    % 4 10
    % 5 10
    % 6 10
    % 7 10
    % 8 10
    % 9 10
    this.NetParamData = this.Block.NetParamData;
    this.NetParamFreq = this.Block.NetParamFreq;
    this.InterpMethod = this.Block.InterpMethod;
    % 13 15
    % 14 15
    this.NoiseDefinedBy = this.Block.NoiseDefinedBy;
    this.NF = this.Block.NF;
    this.FMIN = this.Block.FMIN;
    this.GammaOpt = this.Block.GammaOpt;
    this.RN = this.Block.RN;
    this.NFactor = this.Block.NFactor;
    this.NTemp = this.Block.NTemp;
    % 22 24
    % 23 24
    this.IP3Type = this.Block.IP3Type;
    this.IIP3 = this.Block.IIP3;
    this.OIP3 = this.Block.OIP3;
    this.P1dB = this.Block.P1dB;
    this.PSat = this.Block.PSat;
    this.GCSat = this.Block.GCSat;
    % 30 32
    % 31 32
    this.SourceFreq = this.Block.SourceFreq;
    this.Freq = this.Block.Freq;
    this.AllPlotType = this.Block.AllPlotType;
    this.YOption = this.Block.YOption;
    this.XOption = this.Block.XOption;
    this.PlotZ0 = this.Block.PlotZ0;
end % function
