function components = sptcompp(components)
    % 1 17
    % 2 17
    % 3 17
    % 4 17
    % 5 17
    % 6 17
    % 7 17
    % 8 17
    % 9 17
    % 10 17
    % 11 17
    % 12 17
    % 13 17
    % 14 17
    % 15 17
    % 16 17
    components(1.0).name = 'Signals';
    components(1.0).structName = 'Signal';
    components(1.0).defaultClient = 'sigbrowse';
    components(1.0).multipleSelection = 1.0;
    components(1.0).importFcn = 'importsig';
    components(1.0).types = {'vector',{};'array',{'fontweight','bold'}};
    % 23 24
    components(1.0).verbs.owningClient = 'sigbrowse';
    components(1.0).verbs.buttonLabel = 'View';
    components(1.0).verbs.action = 'view';
    % 27 28
    components(2.0).name = 'Filters';
    components(2.0).structName = 'Filter';
    components(2.0).defaultClient = 'filtview';
    components(2.0).multipleSelection = 1.0;
    components(2.0).importFcn = 'importfilt';
    components(2.0).types = {'imported',{'fontangle','italic'};'design',{}};
    % 34 35
    components(2.0).verbs(1.0).owningClient = 'filtview';
    components(2.0).verbs(1.0).buttonLabel = 'View';
    components(2.0).verbs(1.0).action = 'view';
    components(2.0).verbs(2.0).owningClient = 'filtdes';
    components(2.0).verbs(2.0).buttonLabel = 'New';
    components(2.0).verbs(2.0).action = 'create';
    components(2.0).verbs(3.0).owningClient = 'filtdes';
    components(2.0).verbs(3.0).buttonLabel = 'Edit';
    components(2.0).verbs(3.0).action = 'change';
    components(2.0).verbs(4.0).owningClient = 'applyfilt';
    components(2.0).verbs(4.0).buttonLabel = 'Apply';
    components(2.0).verbs(4.0).action = 'apply';
    % 47 48
    components(3.0).name = 'Spectra';
    components(3.0).structName = 'Spectrum';
    components(3.0).defaultClient = 'spectview';
    components(3.0).multipleSelection = 1.0;
    components(3.0).importFcn = 'importspec';
    components(3.0).types = {'auto',{}};
    components(3.0).verbs(1.0).owningClient = 'spectview';
    components(3.0).verbs(1.0).buttonLabel = 'View';
    components(3.0).verbs(1.0).action = 'view';
    components(3.0).verbs(2.0).owningClient = 'spectview';
    components(3.0).verbs(2.0).buttonLabel = 'Create';
    components(3.0).verbs(2.0).action = 'create';
    components(3.0).verbs(3.0).owningClient = 'spectview';
    components(3.0).verbs(3.0).buttonLabel = 'Update';
    components(3.0).verbs(3.0).action = 'update';
end % function
