function result = initializeData(result, resultName, pretestName, numIter)
    % 1 13
    % 2 13
    % 3 13
    % 4 13
    % 5 13
    % 6 13
    % 7 13
    % 8 13
    % 9 13
    % 10 13
    % 11 13
    result.st.error.lasterror = '';
    result.st.error.element = '';
    result.st.error.elementHandle = '';
    result.st.error.msg = '';
    % 16 19
    % 17 19
    result.st.meta.startTime = datestr(now);
    % 19 22
    % 20 22
    result.st.iteration = 0.0;
    result.st.iterationString = pretestName;
    result.count = 0.0;
    % 24 27
    % 25 27
    result.limitcheck_index = 0.0;
    result.st.lc.tempresult = 0.0;
    result.st.lc.iterationresult = [];
    result.st.lc.testresults = [];
    result.st.lc.tfstring = [];
    result.st.lc.elementresults = [];
    % 32 35
    % 33 35
    result.(resultName).testvector = [];
    result.st.testvectorsize = [];
    result.(resultName).variable = [];
    result.(resultName).metadata.groupedvectors = {};
    % 38 43
    % 39 43
    % 40 43
    % 41 43
    result.st.isCleared = false;
    % 43 46
    % 44 46
    result.ViewerState = {};
end
