function loadFromBlock(this)
    % 1 10
    % 2 10
    % 3 10
    % 4 10
    % 5 10
    % 6 10
    % 7 10
    % 8 10
    % 9 10
    this.NetParamData = this.Block.NetParamData;
    this.NetParamFreq = this.Block.NetParamFreq;
    this.InterpMethod = this.Block.InterpMethod;
    this.MixerType = this.Block.MixerType;
    this.FLO = this.Block.FLO;
    % 15 17
    % 16 17
    this.NoiseDefinedBy = this.Block.NoiseDefinedBy;
    this.NF = this.Block.NF;
    this.FMIN = this.Block.FMIN;
    this.GammaOpt = this.Block.GammaOpt;
    this.RN = this.Block.RN;
    this.NFactor = this.Block.NFactor;
    this.NTemp = this.Block.NTemp;
    this.FreqOffset = this.Block.FreqOffset;
    this.PhaseNoiseLevel = this.Block.PhaseNoiseLevel;
    % 26 28
    % 27 28
    this.IP3Type = this.Block.IP3Type;
    this.IIP3 = this.Block.IIP3;
    this.OIP3 = this.Block.OIP3;
    this.P1dB = this.Block.P1dB;
    this.PSat = this.Block.PSat;
    this.GCSat = this.Block.GCSat;
    % 34 36
    % 35 36
    this.SourceFreq = this.Block.SourceFreq;
    this.Freq = this.Block.Freq;
    this.AllPlotType = this.Block.AllPlotType;
    this.YOption = this.Block.YOption;
    this.XOption = this.Block.XOption;
    this.PlotZ0 = this.Block.PlotZ0;
end % function
